[BAC-1982] - Files API
eNote-GmbH/mozilla-send pull request #1
Opened 2022-07-20 16:48 UTC by didasmbalanya

2022-07-22 18:13 UTC, aesariyev requested changes
Please add some tests for api and storage

2022-07-27 10:18 UTC, aesariyev commented
> Please add some tests for api and storage

upd: Resolved

2022-07-27 10:18 UTC, aesariyev approved these changes

2022-07-27 11:18 UTC, alsprogrammer approved these changes
LGTM!

2022-07-27 11:19 UTC, merged