Feature/resumable - refs #BAC-2037
eNote-GmbH/mozilla-send pull request #6
Opened 2022-08-12 09:35 UTC by alsprogrammer

2022-08-12 10:02 UTC, aesariyev approved these changes

2022-08-12 12:04 UTC, didasmbalanya approved these changes
LGTM

2022-08-15 08:25 UTC, enote-kane requested changes
@aesariyev Please take over on this one in our new sprint for BAC-1983

Also verify that upload without the extra headers or request flow to the standard `/api/upload` endpoint still works as before (single HTTP call).

2022-08-15 08:25 UTC, ghost commented on server/routes/index.js
> +    tusServer.handle(req, res);
We shouldn't expose this extra path.

As we're just using a library here, it should be possible to integrate it directly into `upload.js` and `resumable_upload_done.js`.

Also please take a look at further configuration options to disable default behavior as much as possible, so that we do not expose functionality (e.g. instructions by request HTTP headers to Tus), which we did not intend to publish.

2022-08-15 08:25 UTC, ghost commented on server/routes/index.js
> +    require('./resumable_upload_done.js')
Please rename this to just `upload_done.js`, so we keep the naming pattern/correlation.

2022-08-20 09:14 UTC, aesariyev commented on server/routes/index.js
> +    tusServer.handle(req, res);
Done

2022-08-20 09:14 UTC, aesariyev commented on server/routes/index.js
> +    require('./resumable_upload_done.js')
Done

2022-08-24 12:29 UTC, enote-kane approved these changes

2022-08-24 12:30 UTC, merged